const um = document.getElementById('bt-1')
const dois = document.getElementById('bt-2')
const tres = document.getElementById('bt-3')
const quatro = document.getElementById('bt-4')
const cinco = document.getElementById('bt-5')
const seis = document.getElementById('bt-6')
const sete = document.getElementById('bt-7')
const oito = document.getElementById('bt-8')
const nove = document.getElementById('bt-9')
const zero = document.getElementById('bt-0')
const mais = document.getElementById('bt-somar')
const menos = document.getElementById('bt-subtrair')
const multi = document.getElementById('bt-multiplicacao')
const div = document.getElementById('bt-dividir')

